baseURL: https://samon.netlify.app
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      THIS IS MY PERSONAL WEBSITE WHERE I WILL BE PUBLISHING MY CODING PROJECTS
    title: Samon Sanchuli
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom 
        street: Regents Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: samon.sanchuli@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 20 7000 7000
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Kostis, if you see this error message, please don't deduct marks. I did my best here :)
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/samon_sanchuli
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/somon.sanchooli
  #    - icon: fa-instagram
  #      label: Instagram
  #      url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/samon-sanchuli/my_website
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/samon-sanchuli/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
#      - name: Blogs
        url: blogs
      - name: About Me
        url: blogs/first_project
#      - name: Elements
#        url: elements.html
    menu: Menu
#    subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: resume_picture.jpg
        subtitle: My most recent CV
        title: Resume
        url: blogs/resume
      - image: 
        subtitle: This is the first R project that I undertook
        title: First R Project
        url: blogs/first_project
      - image: tfl_bikes.jpg
        subtitle: This project investigates patterns behind TFL bike rentals
        title: Bike Rentals Project
        url: blogs/bike_challenge
      - image: Human-Capital.png
        subtitle: Inequality and Human Capital Accumulation
        title: Undergraduate Dissertation 
        url: blogs/dissertation
      - image: 
        subtitle: This project investigates the determinants of Airbnb prices in Shanghai
        title: Shanghai Airbnb Project
        url: blogs/airbnb
      - image: 
        subtitle: Investigating Inflation
        title: Consumer Price Index
        url: blogs/consumer
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "My name is Samon Sanchuli and I am a student and London Business School. My goal with this project is to build a portfolio of coding projects as well as other pieces of work. Going forward, I would like to upload progressively more complicated projects. I hope that this website will document my progress and skill development."
    title: About Me
    url: blogs
